services:
  image-generator:
    image: ghcr.io/mkcfdc/image-generator:latest
    container_name: image-generator
    restart: unless-stopped
    ports:
      - "3001:3000"               # Expose only if you need external access
    environment:
      - NODE_ENV=production
      # - PORT=3000           
  la12-addon:
    build:
      context: .
      dockerfile: Dockerfile
    image: la12-addon:latest
    container_name: la12-addon
    restart: unless-stopped
    ports:
      - "7001:7000"
    environment:
      - PORT=7000
      - NODE_ENV=production
      - IMAGE_GENERATOR_BASE_URL=http://localhost:3001
      - TIMEZONE_OFFSET_HOURS=-6
      - SOURCE_TIMEZONE_OFFSET_HOURS=-6
    depends_on:
      - image-generator
