services:
  la12-addon:
    build:
      context: .
      dockerfile: Dockerfile
    image: la12-addon:latest
    container_name: la12-addon
    restart: unless-stopped
    ports:
      - "7000:7000" 
    environment:
      # - PORT=7000
      # - NODE_ENV=production